server:
  port: 10000
  servlet:
    session:
      tracking-modes: COOKIE
      cookie:
        http-only: true
        secure: false
        same-site: lax
      timeout: 10m

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://15.164.96.234:5432/app?serverTimezone=Asia/Seoul
    username: spring
    password: 1234
  session:
    redis:
      repository-type: indexed
      flush-mode: immediate
  data:
    redis:
      host: 15.164.96.234
      port: 6379
  cache:
    type: redis
  profiles:
    active: local
    include: oauth
  mail:
    host: smtp.gmail.com
    port: 587
    username: kimdaae328
    password: xoav buur wpyd cdym
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.kok.domain;com.example.kok.dto
  type-handlers-package: com.example.kok.mybatis.handler
  configuration:
    map-underscore-to-camel-case: true

# openssl rand -base64 32
jwt:
  secret: X6boTs4ejNABCquznMAuLFUvu3yMvu7ICL/X+/tGzus=

aws:
  access-key: AKIART3UT6J6LNJB7L72
  secret-key: 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
  s3:
    bucket-name: kok-bucket
  region: ap-northeast-2